#!/usr/bin/env bash
###################
# Hello this is my personal configuration.
# This file will **definitely** screw up your bash configuration
# if you don't look through it and comment out what you don't need.
# e.g. `ls` -> `lsd`
####
# Terminal Editor
alias vim=$EDITOR
alias nano=$EDITOR
alias edit=$EDITOR
alias e=$EDITOR

alias ssh="TERM=xterm-256color ssh"

###
# GUI bombs
alias top=$PROC_MON

### 
# Git
alias gl="'/usr/bin/ls' --color=auto -d \$(git ls-tree -rt \$(git branch | grep \\* | cut -d \" \" -f2) --name-only)"
alias gr="git reset --soft HEAD~1"
alias grs=gr
alias ghr="git reset --hard HEAD~1"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gd='git diff --color | sed "s/^\([^-+ ]*\)[-+ ]/\\1/" | less -r'

#############
# ls
alias sl='ls'
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'

####
# Helpers
alias cp="cp -i -r"
alias df="df -h"
alias free="free -m"
alias more="less"
alias netstat="ss -lntup"
alias tmux="tmux -u"
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias clr="clear"
alias cls="clear"
alias psg='ps aux | grep'
alias tcurl="curl --socks5 127.0.0.1:9050 "
# alias tre="tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX;"
alias dmesg="dmesg --color=always"

####
# Desktop Helpers
alias vol="pactl -- set-sink-volume 0" # Control volume (pulseaudio) vol +5%
alias explore="xdg-open ."
alias vscode="/usr/bin/code"
alias clipboard="xclip -selection c"
alias open="xdg-open"
alias spotify="spawn snap run spotify"

####
# Python
alias py2="python2"
alias py3="python3"
alias pip2="python -m pip"
alias pip3="python3 -m pip"

###
### Breaking system changes below
###

# https://github.com/sharkdp/bat
alias cat="bat"
# https://github.com/Peltoche/lsd
alias ls="lsd"


